# Generated by Django 4.2.5 on 2023-10-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='decorations',
            field=models.ManyToManyField(to='main_app.decoration'),
        ),
    ]
